name: CI
on:
  push:
    branches: [ main ]

jobs:
  container-test-job:
    runs-on: ubuntu-latest
    container: ghcr.io/autowarefoundation/autoware-universe:latest-cuda
    steps:
      - name: Check out repository
        uses: actions/checkout@v3

      - name: Debug
        run: echo "Hello World"
